sudo: false

language: scala

jdk:
  - oraclejdk8

env:
  - "IDEA_VERSION=191.6183.20;PHP_PLUGIN_URL=https://plugins.jetbrains.com/files/6610/59381/php-191.6183.13.zip" # 2019.1 EAP
  - "IDEA_VERSION=2018.3.4;PHP_PLUGIN_URL=https://plugins.jetbrains.com/files/6610/53883/php-183.5153.36.zip"

install:
   - sbt -DIDEA_VERSION=$IDEA_VERSION -DPHP_PLUGIN_URL=$PHP_PLUGIN_URL test

script:
   - sbt -DIDEA_VERSION=$IDEA_VERSION -DPHP_PLUGIN_URL=$PHP_PLUGIN_URL "; pluginPack ; pluginCompress ; pluginProguard"

matrix:
  allow_failures:
    - env: "IDEA_VERSION=191.6183.20;PHP_PLUGIN_URL=https://plugins.jetbrains.com/files/6610/59381/php-191.6183.13.zip"
