sudo: false

language: scala

jdk:
  - oraclejdk8

env:
  - "IDEA_VERSION=2019.1;PHP_PLUGIN_URL=https://plugins.jetbrains.com/files/6610/60039/php-191.6183.95.zip"

install:
   - sbt -DIDEA_VERSION=$IDEA_VERSION -DPHP_PLUGIN_URL=$PHP_PLUGIN_URL test

script:
   - sbt -DIDEA_VERSION=$IDEA_VERSION -DPHP_PLUGIN_URL=$PHP_PLUGIN_URL "; pluginPack ; pluginCompress ; pluginProguard"

matrix:
  allow_failures: []
