sudo: false

language: scala

jdk:
  - openjdk8

env:
  - "IDEA_VERSION=2019.2;PHP_PLUGIN_URL=https://plugins.jetbrains.com/files/6610/66024/php-192.5728.108.zip"
  - "IDEA_VERSION=2019.2.3;PHP_PLUGIN_URL=https://plugins.jetbrains.com/files/6610/68963/php-192.6817.12.zip"
  - "IDEA_VERSION=193.3793-EAP-CANDIDATE-SNAPSHOT;PHP_PLUGIN_URL=https://plugins.jetbrains.com/files/6610/69228/php.zip"

install:
   - sbt -DIDEA_VERSION=$IDEA_VERSION -DPHP_PLUGIN_URL=$PHP_PLUGIN_URL test

script:
   - sbt -DIDEA_VERSION=$IDEA_VERSION -DPHP_PLUGIN_URL=$PHP_PLUGIN_URL "; pluginPack ; pluginCompress ; pluginProguard"

matrix:
  allow_failures:
    - env: "IDEA_VERSION=193.3793-EAP-CANDIDATE-SNAPSHOT;PHP_PLUGIN_URL=https://plugins.jetbrains.com/files/6610/69228/php.zip"
