sudo: false

language: scala

jdk:
  - oraclejdk8

env:
  - "IDEA_VERSION=2019.1;PHP_PLUGIN_URL=https://plugins.jetbrains.com/files/6610/60039/php-191.6183.95.zip"
  - "IDEA_VERSION=2019.1.1;PHP_PLUGIN_URL=https://plugins.jetbrains.com/files/6610/61026/php-191.6707.66.zip"
  - "IDEA_VERSION=2019.1.2;PHP_PLUGIN_URL=https://plugins.jetbrains.com/files/6610/62069/php-191.7141.52.zip"
install:
   - sbt -DIDEA_VERSION=$IDEA_VERSION -DPHP_PLUGIN_URL=$PHP_PLUGIN_URL test

script:
   - sbt -DIDEA_VERSION=$IDEA_VERSION -DPHP_PLUGIN_URL=$PHP_PLUGIN_URL "; pluginPack ; pluginCompress ; pluginProguard"

matrix:
  allow_failures: []
